name: deploy-dev

on:
  push:
    branches: [dev]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: development
      ref: ${{ github.sha }}
      image_tag: dev-${{ github.sha }}
