name: release-deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # v1.2.3 -> production
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+' # v1.2.3-rc.1 -> staging

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: ${{ contains(github.ref_name, '-rc.') && 'staging' || 'production' }}
      ref: ${{ github.sha }}
      image_tag: ${{ github.ref_name }}
